version: "3"
services:
  users:
    image: tripmaster/users
    ports:
      - 8081:8081
  location:
    image: tripmaster/location
    ports:
      - 8090:8090
  rewards:
    image: tripmaster/rewards
    ports:
      - 8091:8091
  tourguide:
    image: tripmaster/tourguide
    ports:
    - 8080:8080